In [13]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
import yfinance as yf

%matplotlib inline

In [18]:
ticker_symbol = 'BTC-USD'

# Fetch Bitcoin data from Yahoo Finance
df = yf.download(ticker_symbol, start='2015-01-01', end='2024-09-30')

df=df.reset_index()
df.head()

[*********************100%%**********************]  1 of 1 completed

,Date,Open,High,Low,Close,Adj Close,Volume
0,2015-01-01,320.434998,320.434998,314.002991,314.248993,314.248993,8036550
1,2015-01-02,314.079010,315.838989,313.565002,315.032013,315.032013,7860650
2,2015-01-03,314.846008,315.149994,281.082001,281.082001,281.082001,33054400
3,2015-01-04,281.145996,287.230011,257.612000,264.195007,264.195007,55629100
4,2015-01-05,265.084015,278.341003,265.084015,274.473999,274.473999,43962800

In [19]:
df.shape

(3560, 7)

In [20]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3560 entries, 0 to 3559
Data columns (total 7 columns):
 #   Column     Non-Null Count  Dtype
---  ------     --------------  -----
 0   Date       3560 non-null   datetime64[ns]
 1   Open       3560 non-null   float64
 2   High       3560 non-null   float64
 3   Low        3560 non-null   float64
 4   Close      3560 non-null   float64
 5   Adj Close  3560 non-null   float64
 6   Volume     3560 non-null   int64
dtypes: datetime64[ns](1), float64(5), int64(1)
memory usage: 194.8 KB

In [21]:
df.tail()

,Date,Open,High,Low,Close,Adj Close,Volume
3555,2024-09-25,64302.589844,64804.503906,62945.375000,63143.144531,63143.144531,25078377700
3556,2024-09-26,63138.546875,65790.796875,62669.269531,65181.019531,65181.019531,36873129847
3557,2024-09-27,65180.664062,66480.695312,64852.992188,65790.664062,65790.664062,32058813449
3558,2024-09-28,65792.179688,66255.531250,65458.035156,65887.648438,65887.648438,15243637984
3559,2024-09-29,65888.898438,66069.343750,65450.015625,65635.304688,65635.304688,14788214575

In [22]:
# Initialize a flag to track if all values are the same
all_same = True

# Check if the 'Close' and 'Adj Close' values are the same for each row
for i in range(len(df)):
    if df['Close'][i] != df['Adj Close'][i]:
        all_same = False
        break

# Drop 'Adj Close' if all values are the same
if all_same:
    df = df.drop(columns='Adj Close')

# Display the updated DataFrame
df.head()

        Date        Open        High         Low       Close    Volume
0 2015-01-01  320.434998  320.434998  314.002991  314.248993   8036550
1 2015-01-02  314.079010  315.838989  313.565002  315.032013   7860650
2 2015-01-03  314.846008  315.149994  281.082001  281.082001  33054400
3 2015-01-04  281.145996  287.230011  257.612000  264.195007  55629100
4 2015-01-05  265.084015  278.341003  265.084015  274.473999  43962800

In [27]:
df['Month'] = df['Date'].dt.month
df['Day'] = df['Date'].dt.day
df['Year'] = df['Date'].dt.year

In [28]:
df.head()

,Date,Open,High,Low,Close,Volume,Month,Day,Year
0,2015-01-01,320.434998,320.434998,314.002991,314.248993,8036550,1,1,2015
1,2015-01-02,314.079010,315.838989,313.565002,315.032013,7860650,1,2,2015
2,2015-01-03,314.846008,315.149994,281.082001,281.082001,33054400,1,3,2015
3,2015-01-04,281.145996,287.230011,257.612000,264.195007,55629100,1,4,2015
4,2015-01-05,265.084015,278.341003,265.084015,274.473999,43962800,1,5,2015